# Generated by Django 4.2.7 on 2025-11-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
