# Generated by Django 4.2.7 on 2025-11-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userpreference_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='timezone',
            field=models.CharField(blank=True, default='PST', max_length=50),
        ),
    ]
