# Generated by Django 4.2.7 on 2025-11-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userpreference_company_userpreference_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='bcc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='email',
            name='cc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='email',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
